import { defineConfig } from 'vitest/config';
import swc from 'unplugin-swc';

export default defineConfig({
  plugins: [swc.vite({ module: { type: 'es6' } })],
  test: {
    globals: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/__tests__/**',
        'src/**/*.module.ts',
        'src/**/*.controller.ts',
        'src/**/*.guard.ts',
        'src/**/*.strategy.ts',
        'src/**/*.filter.ts',
        'src/**/*.decorator.ts',
        'src/**/dto/**',
        'src/main.ts',
        'src/app.module.ts',
        'src/config/**',
        'src/db/migrations/**',
        'src/db/schema.ts',
        'src/events/**',
        'src/mcp/**',
        'src/plugins/plugin.types.ts',
        'src/user-auth/firebase-auth.service.ts',
        'src/db/db.service.ts',
        'src/db/rls.context.ts',
        'src/db/rls.interceptor.ts',
        'src/db/logging.service.ts',
        'src/memory/ai.service.ts',
        'src/memory/ai-cache.service.ts',
        'src/memory/openrouter.service.ts',
        'src/memory/memory.processor.ts',
        'src/memory/enrich.processor.ts',
        'src/memory/backfill.processor.ts',
        'src/memory/clean.processor.ts',
        'src/memory/decay.processor.ts',
        'src/memory/embed.processor.ts',
        'src/me/me.service.ts',
        'src/memory/memory.service.ts',
        'src/contacts/contacts.service.ts',
        'src/billing/**',
      ],
      thresholds: {
        statements: 65,
        branches: 60,
        functions: 65,
        lines: 65,
      },
    },
  },
});
